// Code generated by MockGen. DO NOT EDIT.
// Source: payments_outbox_worker.go
//
// Generated by this command:
//
//	mockgen -source=payments_outbox_worker.go -destination=mocks/mock_worker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/GargantuaLabs/payment/internal/domain"
	postgres "github.com/GargantuaLabs/payment/internal/repository/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// ClaimBatch mocks base method.
func (m *MockDB) ClaimBatch(ctx context.Context, batchSize int, workerID string, lease time.Duration) ([]postgres.PaymentsOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimBatch", ctx, batchSize, workerID, lease)
	ret0, _ := ret[0].([]postgres.PaymentsOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimBatch indicates an expected call of ClaimBatch.
func (mr *MockDBMockRecorder) ClaimBatch(ctx, batchSize, workerID, lease any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimBatch", reflect.TypeOf((*MockDB)(nil).ClaimBatch), ctx, batchSize, workerID, lease)
}

// MarkOutboxProcessed mocks base method.
func (m *MockDB) MarkOutboxProcessed(ctx context.Context, row *postgres.PaymentsOutbox, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxProcessed", ctx, row, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxProcessed indicates an expected call of MarkOutboxProcessed.
func (mr *MockDBMockRecorder) MarkOutboxProcessed(ctx, row, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxProcessed", reflect.TypeOf((*MockDB)(nil).MarkOutboxProcessed), ctx, row, workerID)
}

// MarkRetryOrFail mocks base method.
func (m *MockDB) MarkRetryOrFail(ctx context.Context, row *postgres.PaymentsOutbox, cause error, maxAttempts int, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRetryOrFail", ctx, row, cause, maxAttempts, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRetryOrFail indicates an expected call of MarkRetryOrFail.
func (mr *MockDBMockRecorder) MarkRetryOrFail(ctx, row, cause, maxAttempts, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRetryOrFail", reflect.TypeOf((*MockDB)(nil).MarkRetryOrFail), ctx, row, cause, maxAttempts, workerID)
}

// MockBalanceProducer is a mock of BalanceProducer interface.
type MockBalanceProducer struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceProducerMockRecorder
	isgomock struct{}
}

// MockBalanceProducerMockRecorder is the mock recorder for MockBalanceProducer.
type MockBalanceProducerMockRecorder struct {
	mock *MockBalanceProducer
}

// NewMockBalanceProducer creates a new mock instance.
func NewMockBalanceProducer(ctrl *gomock.Controller) *MockBalanceProducer {
	mock := &MockBalanceProducer{ctrl: ctrl}
	mock.recorder = &MockBalanceProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceProducer) EXPECT() *MockBalanceProducerMockRecorder {
	return m.recorder
}

// PublishBalance mocks base method.
func (m *MockBalanceProducer) PublishBalance(ctx context.Context, balance *domain.BalanceEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBalance", ctx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBalance indicates an expected call of PublishBalance.
func (mr *MockBalanceProducerMockRecorder) PublishBalance(ctx, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBalance", reflect.TypeOf((*MockBalanceProducer)(nil).PublishBalance), ctx, balance)
}
