// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/GargantuaLabs/payment/internal/domain"
	types "github.com/Krokozabra213/common/types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDBProvider is a mock of DBProvider interface.
type MockDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDBProviderMockRecorder
	isgomock struct{}
}

// MockDBProviderMockRecorder is the mock recorder for MockDBProvider.
type MockDBProviderMockRecorder struct {
	mock *MockDBProvider
}

// NewMockDBProvider creates a new mock instance.
func NewMockDBProvider(ctrl *gomock.Controller) *MockDBProvider {
	mock := &MockDBProvider{ctrl: ctrl}
	mock.recorder = &MockDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBProvider) EXPECT() *MockDBProviderMockRecorder {
	return m.recorder
}

// GetLatestRate mocks base method.
func (m *MockDBProvider) GetLatestRate(ctx context.Context, code domain.CurrencyCode) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRate", ctx, code)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRate indicates an expected call of GetLatestRate.
func (mr *MockDBProviderMockRecorder) GetLatestRate(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRate", reflect.TypeOf((*MockDBProvider)(nil).GetLatestRate), ctx, code)
}

// GetPaymentByID mocks base method.
func (m *MockDBProvider) GetPaymentByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockDBProviderMockRecorder) GetPaymentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockDBProvider)(nil).GetPaymentByID), ctx, id)
}

// MarkTGPaymentInitFailed mocks base method.
func (m *MockDBProvider) MarkTGPaymentInitFailed(ctx context.Context, paymentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTGPaymentInitFailed", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTGPaymentInitFailed indicates an expected call of MarkTGPaymentInitFailed.
func (mr *MockDBProviderMockRecorder) MarkTGPaymentInitFailed(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTGPaymentInitFailed", reflect.TypeOf((*MockDBProvider)(nil).MarkTGPaymentInitFailed), ctx, paymentID)
}

// MarkTGPaymentPending mocks base method.
func (m *MockDBProvider) MarkTGPaymentPending(ctx context.Context, paymentID uuid.UUID, paymentURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTGPaymentPending", ctx, paymentID, paymentURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTGPaymentPending indicates an expected call of MarkTGPaymentPending.
func (mr *MockDBProviderMockRecorder) MarkTGPaymentPending(ctx, paymentID, paymentURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTGPaymentPending", reflect.TypeOf((*MockDBProvider)(nil).MarkTGPaymentPending), ctx, paymentID, paymentURL)
}

// MarkTbankPaymentPending mocks base method.
func (m *MockDBProvider) MarkTbankPaymentPending(ctx context.Context, paymentID uuid.UUID, paymentURL, providerPaymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTbankPaymentPending", ctx, paymentID, paymentURL, providerPaymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTbankPaymentPending indicates an expected call of MarkTbankPaymentPending.
func (mr *MockDBProviderMockRecorder) MarkTbankPaymentPending(ctx, paymentID, paymentURL, providerPaymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTbankPaymentPending", reflect.TypeOf((*MockDBProvider)(nil).MarkTbankPaymentPending), ctx, paymentID, paymentURL, providerPaymentID)
}

// PaymentCancelLock mocks base method.
func (m *MockDBProvider) PaymentCancelLock(ctx context.Context, params domain.PaymentCancelLockParams) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentCancelLock", ctx, params)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaymentCancelLock indicates an expected call of PaymentCancelLock.
func (mr *MockDBProviderMockRecorder) PaymentCancelLock(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentCancelLock", reflect.TypeOf((*MockDBProvider)(nil).PaymentCancelLock), ctx, params)
}

// PaymentFinishCancel mocks base method.
func (m *MockDBProvider) PaymentFinishCancel(ctx context.Context, paymentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentFinishCancel", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PaymentFinishCancel indicates an expected call of PaymentFinishCancel.
func (mr *MockDBProviderMockRecorder) PaymentFinishCancel(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentFinishCancel", reflect.TypeOf((*MockDBProvider)(nil).PaymentFinishCancel), ctx, paymentID)
}

// PaymentFinishRefund mocks base method.
func (m *MockDBProvider) PaymentFinishRefund(ctx context.Context, paymentID uuid.UUID, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentFinishRefund", ctx, paymentID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// PaymentFinishRefund indicates an expected call of PaymentFinishRefund.
func (mr *MockDBProviderMockRecorder) PaymentFinishRefund(ctx, paymentID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentFinishRefund", reflect.TypeOf((*MockDBProvider)(nil).PaymentFinishRefund), ctx, paymentID, amount)
}

// PaymentReserve mocks base method.
func (m *MockDBProvider) PaymentReserve(ctx context.Context, params domain.CreatePaymentParams) (*domain.Payment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentReserve", ctx, params)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PaymentReserve indicates an expected call of PaymentReserve.
func (mr *MockDBProviderMockRecorder) PaymentReserve(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentReserve", reflect.TypeOf((*MockDBProvider)(nil).PaymentReserve), ctx, params)
}

// PaymentRevertLock mocks base method.
func (m *MockDBProvider) PaymentRevertLock(ctx context.Context, paymentID uuid.UUID, lockStatus, revertStatus domain.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentRevertLock", ctx, paymentID, lockStatus, revertStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// PaymentRevertLock indicates an expected call of PaymentRevertLock.
func (mr *MockDBProviderMockRecorder) PaymentRevertLock(ctx, paymentID, lockStatus, revertStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentRevertLock", reflect.TypeOf((*MockDBProvider)(nil).PaymentRevertLock), ctx, paymentID, lockStatus, revertStatus)
}

// TGCompletePayment mocks base method.
func (m *MockDBProvider) TGCompletePayment(ctx context.Context, params domain.TGCompletePaymentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TGCompletePayment", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// TGCompletePayment indicates an expected call of TGCompletePayment.
func (mr *MockDBProviderMockRecorder) TGCompletePayment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TGCompletePayment", reflect.TypeOf((*MockDBProvider)(nil).TGCompletePayment), ctx, params)
}

// TGPrecheckoutApprove mocks base method.
func (m *MockDBProvider) TGPrecheckoutApprove(ctx context.Context, params domain.TGPrecheckoutApproveParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TGPrecheckoutApprove", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// TGPrecheckoutApprove indicates an expected call of TGPrecheckoutApprove.
func (mr *MockDBProviderMockRecorder) TGPrecheckoutApprove(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TGPrecheckoutApprove", reflect.TypeOf((*MockDBProvider)(nil).TGPrecheckoutApprove), ctx, params)
}

// TbankCompletePayment mocks base method.
func (m *MockDBProvider) TbankCompletePayment(ctx context.Context, params domain.TbankCompleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TbankCompletePayment", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// TbankCompletePayment indicates an expected call of TbankCompletePayment.
func (mr *MockDBProviderMockRecorder) TbankCompletePayment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TbankCompletePayment", reflect.TypeOf((*MockDBProvider)(nil).TbankCompletePayment), ctx, params)
}

// TbankUpdateStatus mocks base method.
func (m *MockDBProvider) TbankUpdateStatus(ctx context.Context, params domain.TbankUpdateStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TbankUpdateStatus", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// TbankUpdateStatus indicates an expected call of TbankUpdateStatus.
func (mr *MockDBProviderMockRecorder) TbankUpdateStatus(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TbankUpdateStatus", reflect.TypeOf((*MockDBProvider)(nil).TbankUpdateStatus), ctx, params)
}

// MockTGProvider is a mock of TGProvider interface.
type MockTGProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTGProviderMockRecorder
	isgomock struct{}
}

// MockTGProviderMockRecorder is the mock recorder for MockTGProvider.
type MockTGProviderMockRecorder struct {
	mock *MockTGProvider
}

// NewMockTGProvider creates a new mock instance.
func NewMockTGProvider(ctrl *gomock.Controller) *MockTGProvider {
	mock := &MockTGProvider{ctrl: ctrl}
	mock.recorder = &MockTGProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTGProvider) EXPECT() *MockTGProviderMockRecorder {
	return m.recorder
}

// AnswerPreCheckout mocks base method.
func (m *MockTGProvider) AnswerPreCheckout(ctx context.Context, preCheckout domain.PreCheckoutPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerPreCheckout", ctx, preCheckout)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerPreCheckout indicates an expected call of AnswerPreCheckout.
func (mr *MockTGProviderMockRecorder) AnswerPreCheckout(ctx, preCheckout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerPreCheckout", reflect.TypeOf((*MockTGProvider)(nil).AnswerPreCheckout), ctx, preCheckout)
}

// Cancel mocks base method.
func (m *MockTGProvider) Cancel(ctx context.Context, userID types.PositiveInt[int64], tgPaymentChargeID types.NonEmptyString) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, userID, tgPaymentChargeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockTGProviderMockRecorder) Cancel(ctx, userID, tgPaymentChargeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockTGProvider)(nil).Cancel), ctx, userID, tgPaymentChargeID)
}

// Init mocks base method.
func (m *MockTGProvider) Init(ctx context.Context, payload *domain.TGInit, idempotencyKey string) (*domain.TGInitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, payload, idempotencyKey)
	ret0, _ := ret[0].(*domain.TGInitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockTGProviderMockRecorder) Init(ctx, payload, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockTGProvider)(nil).Init), ctx, payload, idempotencyKey)
}

// MockTbankProvider is a mock of TbankProvider interface.
type MockTbankProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTbankProviderMockRecorder
	isgomock struct{}
}

// MockTbankProviderMockRecorder is the mock recorder for MockTbankProvider.
type MockTbankProviderMockRecorder struct {
	mock *MockTbankProvider
}

// NewMockTbankProvider creates a new mock instance.
func NewMockTbankProvider(ctrl *gomock.Controller) *MockTbankProvider {
	mock := &MockTbankProvider{ctrl: ctrl}
	mock.recorder = &MockTbankProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTbankProvider) EXPECT() *MockTbankProviderMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockTbankProvider) Cancel(ctx context.Context, paymentID types.NonEmptyString) (*domain.TbankCancel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, paymentID)
	ret0, _ := ret[0].(*domain.TbankCancel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockTbankProviderMockRecorder) Cancel(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockTbankProvider)(nil).Cancel), ctx, paymentID)
}

// Init mocks base method.
func (m *MockTbankProvider) Init(ctx context.Context, payload *domain.TbankInit, idempotencyKey string) (*domain.TbankInitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, payload, idempotencyKey)
	ret0, _ := ret[0].(*domain.TbankInitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockTbankProviderMockRecorder) Init(ctx, payload, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockTbankProvider)(nil).Init), ctx, payload, idempotencyKey)
}

// VerifyWebhook mocks base method.
func (m *MockTbankProvider) VerifyWebhook(payload map[string]string, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", payload, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockTbankProviderMockRecorder) VerifyWebhook(payload, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockTbankProvider)(nil).VerifyWebhook), payload, token)
}
